# Generated by Django 4.2.16 on 2024-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-12-07 19:47:02.364978', max_length=100),
        ),
    ]
