# Generated by Django 4.2.16 on 2024-12-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-12-08 09:04:27.945992', max_length=100),
        ),
    ]
