# Generated by Django 4.2.13 on 2024-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-12-18 19:46:42.261624', max_length=100),
        ),
    ]
